resource "random_password" "bt_id" {
  # kubeadm bootstrap-token ID: 6 chars, regex [a-z0-9]{6}. Earlier this was
  # numeric-only — only ~20 bits (1M possibilities), small enough that within
  # the 24h TTL an attacker spamming join attempts could collide on the ID and
  # interfere with legitimate joins. Base36 brings it to ~31 bits (~2B).
  #
  # random_password (vs random_string) marks .result sensitive, so the token
  # — which is plaintext credential material with a 24h TTL — is redacted in
  # `terraform plan` / `terraform show` output.
  length  = 6
  special = false
  upper   = false
  lower   = true
  numeric = true
}

resource "random_password" "bt_secret" {
  # kubeadm bootstrap-token secret: 16 chars, regex [a-z0-9]{16}. ~83 bits.
  # See bt_id above for why this is random_password rather than random_string.
  length  = 16
  special = false
  upper   = false
  lower   = true
  numeric = true
}

resource "random_id" "cert_key" {
  byte_length = 32
}

resource "random_id" "encryption_key" {
  byte_length = 32
}

resource "tls_private_key" "node_host_key" {
  count     = var.cp_count + var.worker_count
  algorithm = "ED25519"
}

# Cluster CA — generated in TF rather than auto-generated by `kubeadm init`.
# Two reasons:
#  1. `kubeadm init` re-generates a fresh CA on every cluster build, which
#     means joining nodes need `unsafeSkipCAVerification: true` (no way to
#     pin a hash that the CA hasn't been issued yet). Owning the CA in TF
#     lets us pre-compute the SubjectPublicKeyInfo SHA256 and pin it via
#     `caCertHashes` — closing the join-time MITM window.
#  2. The CA persists in tfstate across destroy/apply, so kubeconfigs from
#     before a destroy still validate against the new cluster's apiserver.
#     (Apiserver leaf cert is rotated by kubeadm on each rebuild but stays
#     signed by the same CA.)
#
# CA private key is in tfstate; tfstate is now 0600 (see apply.sh wrapper).
resource "tls_private_key" "cluster_ca" {
  algorithm = "RSA"
  rsa_bits  = 4096

  # The CA private key is the trust root for the entire cluster + every
  # admin client cert + the apiserver cert. A blind `terraform taint` would
  # rotate it without invalidating in-cluster certs (apiserver would still
  # serve the old chain on next restart since kubeadm regenerates leaf
  # certs from whatever CA it finds in /etc/kubernetes/pki). prevent_destroy
  # forces an explicit override before terraform will recreate it.
  lifecycle {
    prevent_destroy = true
  }
}

resource "tls_self_signed_cert" "cluster_ca" {
  private_key_pem       = tls_private_key.cluster_ca.private_key_pem
  is_ca_certificate     = true
  validity_period_hours = 87600 # 10 years
  early_renewal_hours   = 8760  # rotate 1 year before expiry
  allowed_uses = [
    "cert_signing",
    "crl_signing",
    "key_encipherment",
    "digital_signature",
  ]
  subject {
    common_name = "kubernetes"
  }
}

# kubeadm `caCertHashes` uses SHA256 of the CA cert's SubjectPublicKeyInfo
# (DER-encoded), NOT of the cert itself. Helper script does the openssl
# dance because it's not expressible in pure HCL.
data "external" "ca_cert_hash" {
  program = ["bash", "${path.module}/scripts/spki-sha256.sh"]
  query = {
    cert_pem = tls_self_signed_cert.cluster_ca.cert_pem
  }
}

locals {
  ca_cert_hash = data.external.ca_cert_hash.result.hash
}
