locals {
  ssh_config_content = join("\n\n", concat(
    [
      "# SSH config for cluster '${var.cluster_name}' (via LB jump host)\n# Generated by Terraform — do not edit by hand.\n\nHost ${var.cluster_name}-cp-* ${var.cluster_name}-worker-*\n  User root\n  IdentityFile ${local.ssh_private_key_abs}\n  ProxyJump k8s",
    ],

    # IPv4 jump host via LB
    [
      "Host k8s\n  HostName ${hcloud_load_balancer.k8s_api.ipv4}\n  Port ${var.kube_api_lb_ssh_port}\n  User root\n  IdentityFile ${local.ssh_private_key_abs}",
    ],

    # IPv6 jump host via LB
    [
      "Host k8s-v6\n  HostName ${hcloud_load_balancer.k8s_api.ipv6}\n  Port ${var.kube_api_lb_ssh_port}\n  User root\n  IdentityFile ${local.ssh_private_key_abs}",
    ],

    # CP nodes via private IPv4 (jumped through k8s)
    [for i in range(var.cp_count) :
      "Host ${local.cp_node_names[i]}\n  HostName ${local.cp_node_ips[i]}"
    ],

    # Worker nodes via private IPv4 (jumped through k8s)
    [for i in range(var.worker_count) :
      "Host ${local.worker_node_names[i]}\n  HostName ${local.worker_node_ips[i]}"
    ],

    # CP nodes via public IPv6 (jumped through k8s-v6)
    [for i in range(var.cp_count) :
      "Host ${local.cp_node_names[i]}-v6\n  HostName ${cidrhost(hcloud_server.cp[i].ipv6_network, 1)}\n  ProxyJump k8s-v6"
    ],

    # Worker nodes via public IPv6 (jumped through k8s-v6)
    [for i in range(var.worker_count) :
      "Host ${local.worker_node_names[i]}-v6\n  HostName ${cidrhost(hcloud_server.worker[i].ipv6_network, 1)}\n  ProxyJump k8s-v6"
    ]
  ))

  ssh_config_path = pathexpand("~/.ssh/config.d/terraform-k8s.conf")
}

resource "null_resource" "ssh_config_dir" {
  triggers = { dir = local.ssh_config_path }

  provisioner "local-exec" {
    interpreter = ["bash", "-c"]
    command     = "mkdir -p ~/.ssh/config.d"
  }
}

resource "local_file" "ssh_config" {
  filename        = local.ssh_config_path
  content         = local.ssh_config_content
  file_permission = "0600"

  depends_on = [null_resource.ssh_config_dir]
}

resource "null_resource" "ssh_config_include" {
  triggers = { content_hash = sha256(local.ssh_config_content) }

  provisioner "local-exec" {
    interpreter = ["bash", "-c"]
    command     = <<-EOT
      set -e
      [ -f ~/.ssh/config ] || touch ~/.ssh/config
      chmod 600 ~/.ssh/config
      grep -q '^Include ~/.ssh/config.d/\*.conf$' ~/.ssh/config || echo 'Include ~/.ssh/config.d/*.conf' >> ~/.ssh/config
    EOT
  }

  depends_on = [local_file.ssh_config]
}
